// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Button7;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_ImageWifiSignal;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonHotspot;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Spinner2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image12;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
// CUSTOM VARIABLES

// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES


// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img1_png);    // assets/img1.png
LV_IMG_DECLARE(ui_img_img2_png);    // assets/img2.png
LV_IMG_DECLARE(ui_img_img4_png);    // assets/img4.png
LV_IMG_DECLARE(ui_img_img3_png);    // assets/img3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_background_moderen_png);    // assets/background_moderen.png
LV_IMG_DECLARE(ui_img_menerima_semua_payment_yang_dapat_menggunakan_qris_png);
LV_IMG_DECLARE(ui_img_wifi_cross_png);    // assets/wifi_cross.png - WiFi no signal indicator
LV_IMG_DECLARE(ui_img_1944009510);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
