// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image9, &ui_img_img1_png);
    lv_obj_set_width(ui_Image9, 240);
    lv_obj_set_height(ui_Image9, 320);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 163);
    lv_obj_set_height(ui_Spinner2, 153);
    lv_obj_set_x(ui_Spinner2, 8);
    lv_obj_set_y(ui_Spinner2, -12);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -4);
    lv_obj_set_y(ui_Button2, -130);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
