// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "../safe_page.h"
#include "esp_log.h"
#include <stdio.h>
#include <string.h>
#include "my_global_lib.h"

//static const char *TAG = "ui_Screen9";

// Timer untuk monitoring ui_Label11
static lv_timer_t *label11_monitor_timer = NULL;

void screen9_event_handler(lv_event_t *e);
static void label11_monitor_callback(lv_timer_t *timer);

// Timer callback untuk memeriksa ui_Label11
static void label11_monitor_callback(lv_timer_t *timer)
{
    if (ui_Label11 != NULL) {
        const char *text = lv_label_get_text(ui_Label11);
        
        // Periksa jika text kosong, null, atau hanya berisi whitespace
        if (text == NULL || strlen(text) == 0 || 
            (strlen(text) == 1 && text[0] == ' ') ||
            strcmp(text, "") == 0) {
            
            DEBUG_PRINTLN("ui_Label11 is empty, forcing go to page6");
            
            // Stop timer sebelum pindah halaman
            if (label11_monitor_timer != NULL) {
                lv_timer_delete(label11_monitor_timer);
                label11_monitor_timer = NULL;
            }
            
            // Paksa pindah ke halaman 6
            lv_async_call(go_page6, NULL);
        } else {
            DEBUG_PRINTLN("ui_Label11 content: '%s'", text);
        }
    } else {
        DEBUG_PRINTLN("ui_Label11 is NULL");
        
        // Stop timer jika ui_Label11 adalah NULL
        if (label11_monitor_timer != NULL) {
            lv_timer_delete(label11_monitor_timer);
            label11_monitor_timer = NULL;
        }
        
        // Paksa pindah ke halaman 6
        lv_async_call(go_page6, NULL);
    }
}

void screen9_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_SCREEN_LOADED)
    {
        // Ini dipanggil setelah screen tampil
        DEBUG_PRINTLN("Screen9 loaded!");
        
        // Mulai timer untuk memeriksa ui_Label11 setiap 1 detik
        if (label11_monitor_timer == NULL) {
            label11_monitor_timer = lv_timer_create(label11_monitor_callback, 1000, NULL);
            DEBUG_PRINTLN("Label11 monitor timer started");
        }
    }
    else if (code == LV_EVENT_SCREEN_UNLOADED)
    {
        // Screen akan di-unload, hentikan timer
        DEBUG_PRINTLN("Screen9 unloaded!");
        
        if (label11_monitor_timer != NULL) {
            lv_timer_delete(label11_monitor_timer);
            label11_monitor_timer = NULL;
            DEBUG_PRINTLN("Label11 monitor timer stopped");
        }
    }
}

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Screen9, screen9_event_handler, LV_EVENT_ALL, NULL);

    ui_Image5 = lv_image_create(ui_Screen9);
    lv_image_set_src(ui_Image5, &ui_img_1944009510);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 0);
    lv_obj_set_y(ui_Image5, -1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -6);
    lv_obj_set_y(ui_Label9, 65);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Batas waktu");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Batas Waktu
    ui_Label10 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, 97);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "0");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Uang Sisa
    ui_Label11 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -4);
    lv_obj_set_y(ui_Label11, -43);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "0");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
