// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "../safe_page.h"
#include "esp_log.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "nvs_helper.h"
#include "usr_k2_lan.h"
#include "my_global_lib.h"

#define GPIO_OUTPUT_PIN 26 // relay output pin

//static const char *TAG = "ui_Screen6";

void screen6_event_handler(lv_event_t *e);
static void change_to_screen2(lv_timer_t * timer);

// Timer callback untuk pindah ke screen8
static void change_to_screen2(lv_timer_t * timer)
{
    DEBUG_PRINTLN("Pindah ke screen 2");
    // Pindahkan screen ke Screen8
    lv_async_call(go_page2, NULL);
}

void screen6_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_SCREEN_LOADED)
    {
        // Ini dipanggil setelah screen tampil
        DEBUG_PRINTLN("Screen6 loaded!");

        int32_t valueDuty;
        int32_t valueDuration;
        int32_t valueQRPulse;
        if (load_nvs_i32("storage", "duty", &valueDuty) == ESP_OK)
        {
            //ESP_LOGI("APP", "Loaded duty: %d", (int)valueDuty);
        } else {
            valueDuty = 100;
        }
        if (load_nvs_i32("storage", "duration", &valueDuration) == ESP_OK)
        {
            //ESP_LOGI("APP", "Loaded pulse: %d", (int)valueDuration);
        } else {
            valueDuration = 100;
        }
        if (load_nvs_i32("storage", "qrpulse", &valueQRPulse) == ESP_OK)
        {
            //ESP_LOGI("APP", "Loaded pulse: %d", (int)valuePulse);
        } else {
            valueQRPulse = 0;
        }

        /* Begin QRIS Executing contact */
        if(PAYMENT_ROUTE.PaymentType == 2) {
            DEBUG_PRINTLN("QRIS Executing contact");
            // trigger output
            // Kedipkan 3 kali
            for (int i = 0; i < valueQRPulse; i++) {
                gpio_set_level(GPIO_OUTPUT_PIN, 1); // HIGH
                vTaskDelay(pdMS_TO_TICKS((int)valueDuty)); // duty

                gpio_set_level(GPIO_OUTPUT_PIN, 0); // LOW
                vTaskDelay(pdMS_TO_TICKS((int)valueDuration)); // duration
            }

            // (opsional) Setelah itu mati terus
            gpio_set_level(GPIO_OUTPUT_PIN, 0);
        }
         /* End QRIS Executing contact */

        // buat efek sukses
        // Buat timer 2000ms (2 detik), sekali jalan (oneshot)
        lv_timer_t *timer = lv_timer_create(change_to_screen2, 2000, NULL);
        lv_timer_set_repeat_count(timer, 1); // supaya timer jalan sekali saja

        // ini digunakan untuk trigger output relay
        //xTaskCreate(request_midtrans_check_task, "request_midtrans_check_task", 4096, NULL, 5, NULL);

        PAYMENT_ROUTE.PaymentType = 0;
    }
}

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Screen6, screen6_event_handler, LV_EVENT_ALL, NULL);

    ui_Image3 = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_Image3, &ui_img_5_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -2);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Pembayaran anda Berhasil!");

}