// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "../safe_page.h"
#include "../my_wifi.h"
#include "esp_log.h"
#include <stdio.h>
#include <string.h>
#include "nvs_helper.h"
#include "my_global_lib.h"

//static const char *TAG = "ui_Screen4";
static void change_to_screen2(lv_timer_t *timer);
static void clear_timeout_message(lv_timer_t *timer);
static void update_network_status(lv_timer_t *timer);
static void resume_network_status(lv_timer_t *timer);
static void wifi_status_update_callback(const char *message, int color_r, int color_g, int color_b);
void screen4_event_handler(lv_event_t *e);
void screen4_set_message(const char *message);
void screen4_set_payment_timeout(bool timeout_status);
void screen4_pause_network_status(bool pause_status);

// Global reference untuk label
static lv_obj_t *label_no_internet = NULL;

// Global variable untuk status timeout pembayaran
static bool payment_timeout_occurred = false;
static lv_timer_t *timeout_display_timer = NULL;
static lv_timer_t *network_status_timer = NULL;
static bool network_status_paused = false;

void screen4_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_SCREEN_LOADED)
    {
        // Ini dipanggil setelah screen tampil
        DEBUG_PRINTLN("Screen4 loaded!");
        
        // Set callback setelah screen loaded dan label sudah tersedia
        DEBUG_PRINTLN("Setting WiFi callback after screen loaded");
        my_wifi_set_status_callback(wifi_status_update_callback);
        
        // Test callback langsung
        //printf("Testing callback immediately...\n");
        //my_wifi_update_status("Terjadi kesalahan sistem", 255, 255, 255); // Putih untuk loading

        // Buat timer 2000ms (2 detik), sekali jalan (oneshot)
        lv_timer_t *timer = lv_timer_create(change_to_screen2, 2000, NULL);
        lv_timer_set_repeat_count(timer, 1); // supaya timer jalan sekali saja

        // Pause network status update saat pertama kali masuk screen4
        network_status_paused = true;
        DEBUG_PRINTLN("Network status updates paused for initial period");

        // Buat timer untuk update status jaringan setiap 500ms (tetapi di-pause dulu)
        network_status_timer = lv_timer_create(update_network_status, 500, NULL);
        lv_timer_set_repeat_count(network_status_timer, -1); // timer berulang
        
        // Buat timer untuk resume network status update setelah 3 detik
        lv_timer_t *resume_timer = lv_timer_create(resume_network_status, 3000, NULL);
        lv_timer_set_repeat_count(resume_timer, 1); // sekali saja
    }
}

// Fungsi untuk update status jaringan
static void update_network_status(lv_timer_t *timer)
{
    if (label_no_internet == NULL) return;
    
    // Skip update jika sedang di-pause
    if (network_status_paused) {
        DEBUG_PRINTLN("Network status update paused");
        return;
    }

    // Prioritas tertinggi: tampilkan pesan timeout pembayaran jika terjadi
    if (payment_timeout_occurred) {
        lv_label_set_text(label_no_internet, "Pembayaran kadaluarsa");
        lv_obj_set_style_text_color(label_no_internet, lv_color_make(255, 165, 0), LV_PART_MAIN); // Orange
        return;
    }

    // Check network type - disable WiFi status check if LAN mode is active
    int32_t is_wifiorlan = 0;
    const char *nvs_namespace = "storage";
    esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
    
    if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
        // LAN mode active - show "Jaringan terhubung" without WiFi check
        lv_label_set_text(label_no_internet, "Jaringan terhubung");
        lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
        return;
    }

    // Status jaringan normal untuk WiFi mode jika tidak ada timeout
    if (my_wifi_is_connected() == 1) {
        lv_label_set_text(label_no_internet, "Jaringan terhubung");
        lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
    } else {
        lv_label_set_text(label_no_internet, "Jaringan tidak tersedia");
        lv_obj_set_style_text_color(label_no_internet, lv_color_white(), LV_PART_MAIN); // Putih
    }
}

// Callback function untuk update status dari my_wifi.c
static void wifi_status_update_callback(const char *message, int color_r, int color_g, int color_b)
{
    if (label_no_internet == NULL) {
        DEBUG_PRINTLN("Label not initialized yet, cannot update");
        return;
    }
    
    // Jangan update jika sedang menampilkan pesan timeout
    if (payment_timeout_occurred) {
        DEBUG_PRINTLN("Payment timeout active, ignoring wifi status update");
        return;
    }
    
    DEBUG_PRINTLN("Updating label text to: %s with color RGB(%d,%d,%d)", message, color_r, color_g, color_b);
    
    // Gunakan lv_async_call untuk memastikan thread safety
    typedef struct {
        char message[64];
        int color_r, color_g, color_b;
    } update_data_t;
    
    static update_data_t update_data;
    strncpy(update_data.message, message, sizeof(update_data.message) - 1);
    update_data.message[sizeof(update_data.message) - 1] = '\0';
    update_data.color_r = color_r;
    update_data.color_g = color_g;
    update_data.color_b = color_b;
    
    // Update label dalam thread LVGL
    lv_label_set_text(label_no_internet, update_data.message);
    lv_obj_set_style_text_color(label_no_internet, lv_color_make(update_data.color_r, update_data.color_g, update_data.color_b), LV_PART_MAIN);
}

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_Screen4, screen4_event_handler, LV_EVENT_ALL, NULL);

    // Set callback untuk WiFi status update
    my_wifi_set_status_callback(wifi_status_update_callback);

    // halaman gagal
    ui_Image12 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image12, &ui_img_img3_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // Label untuk pesan jaringan (dinamis)
    label_no_internet = lv_label_create(ui_Screen4);
    // Set text awal berdasarkan status WiFi
    if (my_wifi_is_connected() == 1) {
        lv_label_set_text(label_no_internet, "Jaringan terhubung");
        lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
    } else {
        lv_label_set_text(label_no_internet, "Jaringan tidak tersedia");
        lv_obj_set_style_text_color(label_no_internet, lv_color_white(), LV_PART_MAIN); // Putih
    }
    lv_obj_set_align(label_no_internet, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(label_no_internet, -80); // Posisi lebih tinggi dari bawah
    lv_obj_set_style_text_font(label_no_internet, &lv_font_montserrat_14, LV_PART_MAIN);
}

// Timer callback untuk pindah ke screen8
static void change_to_screen2(lv_timer_t *timer)
{
    // Reset ISR enable
    is_payment_isr_enabled = true; // enable isr bill acceptor

    DEBUG_PRINTLN("Pindah ke screen 2");
    // Pindahkan screen ke Screen2
    lv_async_call(go_page2, NULL);
}

// Timer callback untuk membersihkan pesan timeout setelah durasi tertentu
static void clear_timeout_message(lv_timer_t *timer)
{
    DEBUG_PRINTLN("Clearing payment timeout message");
    payment_timeout_occurred = false;
    timeout_display_timer = NULL;
    
    // Update status jaringan normal
    if (label_no_internet != NULL) {
        // Check network type
        int32_t is_wifiorlan = 0;
        const char *nvs_namespace = "storage";
        esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
        
        if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
            // LAN mode - always show connected
            lv_label_set_text(label_no_internet, "Jaringan terhubung");
            lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
        } else {
            // WiFi mode - check actual connection
            if (my_wifi_is_connected() == 1) {
                lv_label_set_text(label_no_internet, "Jaringan terhubung");
                lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
            } else {
                lv_label_set_text(label_no_internet, "Jaringan tidak tersedia");
                lv_obj_set_style_text_color(label_no_internet, lv_color_white(), LV_PART_MAIN); // Putih
            }
        }
    }
}

// Timer callback untuk resume network status update
static void resume_network_status(lv_timer_t *timer)
{
    DEBUG_PRINTLN("Resuming network status updates");
    network_status_paused = false;
    
    // Lakukan update langsung setelah resume
    if (label_no_internet != NULL && !payment_timeout_occurred) {
        // Check network type
        int32_t is_wifiorlan = 0;
        const char *nvs_namespace = "storage";
        esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
        
        if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
            // LAN mode - always show connected
            lv_label_set_text(label_no_internet, "Jaringan terhubung");
            lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
        } else {
            // WiFi mode - check actual connection
            if (my_wifi_is_connected() == 1) {
                lv_label_set_text(label_no_internet, "Jaringan terhubung");
                lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
            } else {
                lv_label_set_text(label_no_internet, "Jaringan tidak tersedia");
                lv_obj_set_style_text_color(label_no_internet, lv_color_white(), LV_PART_MAIN); // Putih
            }
        }
    }
}

// Fungsi untuk mengatur pesan khusus di halaman 4
void screen4_set_message(const char *message)
{
    if (label_no_internet != NULL && message != NULL) {
        lv_label_set_text(label_no_internet, message);
        lv_obj_set_style_text_color(label_no_internet, lv_color_make(255, 255, 0), LV_PART_MAIN); // Kuning untuk pesan khusus
        DEBUG_PRINTLN("Screen4 message set to: %s", message);
    }
}

// Fungsi untuk mengatur status timeout pembayaran
void screen4_set_payment_timeout(bool timeout_status)
{
    payment_timeout_occurred = timeout_status;
    DEBUG_PRINTLN("Payment timeout status set to: %s", timeout_status ? "true" : "false");
    
    if (timeout_status) {
        // Update label langsung jika timeout terjadi
        if (label_no_internet != NULL) {
            lv_label_set_text(label_no_internet, "Pembayaran kadaluarsa");
            lv_obj_set_style_text_color(label_no_internet, lv_color_make(255, 165, 0), LV_PART_MAIN); // Orange
        }
        
        // Hapus timer lama jika ada
        if (timeout_display_timer != NULL) {
            lv_timer_del(timeout_display_timer);
        }
        
        // Buat timer untuk menampilkan pesan timeout selama 5 detik
        timeout_display_timer = lv_timer_create(clear_timeout_message, 5000, NULL);
        lv_timer_set_repeat_count(timeout_display_timer, 1); // Sekali saja
        
        DEBUG_PRINTLN("Payment timeout message will be displayed for 5 seconds");
    } else {
        // Hapus timer jika timeout dibatalkan manual
        if (timeout_display_timer != NULL) {
            lv_timer_del(timeout_display_timer);
            timeout_display_timer = NULL;
        }
    }
}

// Fungsi untuk pause/resume network status update secara manual
void screen4_pause_network_status(bool pause_status)
{
    network_status_paused = pause_status;
    DEBUG_PRINTLN("Network status updates %s", pause_status ? "paused" : "resumed");
    
    // Jika resume, lakukan update langsung
    if (!pause_status && label_no_internet != NULL && !payment_timeout_occurred) {
        // Check network type
        int32_t is_wifiorlan = 0;
        const char *nvs_namespace = "storage";
        esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
        
        if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
            // LAN mode - always show connected
            lv_label_set_text(label_no_internet, "Jaringan terhubung");
            lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
        } else {
            // WiFi mode - check actual connection
            if (my_wifi_is_connected() == 1) {
                lv_label_set_text(label_no_internet, "Jaringan terhubung");
                lv_obj_set_style_text_color(label_no_internet, lv_color_make(0, 255, 0), LV_PART_MAIN); // Hijau
            } else {
                lv_label_set_text(label_no_internet, "Jaringan tidak tersedia");
                lv_obj_set_style_text_color(label_no_internet, lv_color_white(), LV_PART_MAIN); // Putih
            }
        }
    }
}