// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "esp_event.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_log.h"
#include "string.h"
#include "usr_k2_lan.h"
#include "../safe_page.h"
#include "my_global_lib.h"
#include "my_wifi.h"
#include "nvs_helper.h"

//static const char *TAG = "ui_Screen2";
static uint32_t press_start_time = 0;

// Add task control variables to prevent memory leak
static volatile bool payment_task_running = false;
static volatile int active_payment_tasks = 0;
#define MAX_CONCURRENT_PAYMENT_TASKS 1

// WiFi signal blinking variables
static lv_timer_t *wifi_blink_timer = NULL;
static lv_timer_t *wifi_status_check_timer = NULL;
static bool wifi_blink_state = true;

void button_cb_call_midtrans(lv_event_t *e);
void screen2_event_handler(lv_event_t *e);
void hotspot_event_cb(lv_event_t *e);
void payment_request_task(void *pvParameters);
void update_wifi_signal_indicator(void);
void wifi_blink_timer_cb(lv_timer_t *timer);
void wifi_status_check_timer_cb(lv_timer_t *timer);
bool check_internet_connectivity(void);
void payment_complete_callback(void *param);

void screen2_event_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_SCREEN_LOADED)
    {
        // Ini dipanggil setelah screen tampil
        DEBUG_PRINTLN("Screen2 loaded!");

        // button kembali bisa diclick
        lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);  // Hapus status disable
        lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE); // Tambahkan klik lagi

        // Sembunyikan spinner (init tersembunyi)
        lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
        
        // Initialize WiFi signal indicator
        update_wifi_signal_indicator();
        
        // Start periodic WiFi status check timer (every 5 seconds to reduce load)
        if (wifi_status_check_timer == NULL) {
            wifi_status_check_timer = lv_timer_create(wifi_status_check_timer_cb, 5000, NULL);
            if (wifi_status_check_timer != NULL) {
                lv_timer_set_repeat_count(wifi_status_check_timer, -1); // repeat indefinitely
                DEBUG_PRINTLN("WiFi status check timer created successfully");
            } else {
                DEBUG_PRINTLN("Failed to create WiFi status check timer");
            }
        }
    }
    else if (code == LV_EVENT_SCREEN_UNLOADED)
    {
        // Cleanup when screen is unloaded
        if (wifi_blink_timer != NULL) {
            lv_timer_delete(wifi_blink_timer);
            wifi_blink_timer = NULL;
        }
        if (wifi_status_check_timer != NULL) {
            lv_timer_delete(wifi_status_check_timer);
            wifi_status_check_timer = NULL;
        }
        DEBUG_PRINTLN("Screen2 unloaded - cleanup completed");
        
        // Reset task control variables
        payment_task_running = false;
        active_payment_tasks = 0;
        
        // Update WiFi signal indicator
        update_wifi_signal_indicator();
    }
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_Screen2, screen2_event_handler, LV_EVENT_ALL, NULL);

    ui_Image10 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image10, &ui_img_img2_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    
    // Pindahkan image ke layer paling belakang
    lv_obj_move_to_index(ui_Image10, 0);

    // WiFi signal indicator - red circle
    ui_ImageWifiSignal = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ImageWifiSignal, 20);  // Diameter bulat
    lv_obj_set_height(ui_ImageWifiSignal, 20); // Diameter bulat
    lv_obj_set_x(ui_ImageWifiSignal, -100);  // Posisi kiri atas
    lv_obj_set_y(ui_ImageWifiSignal, -140);
    lv_obj_set_align(ui_ImageWifiSignal, LV_ALIGN_CENTER);
    
    // Pindahkan ke layer paling atas agar tidak tertutup
    lv_obj_move_foreground(ui_ImageWifiSignal);
    
    // Buat bulat dengan radius setengah dari width/height
    lv_obj_set_style_radius(ui_ImageWifiSignal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Set warna merah untuk indikator
    lv_obj_set_style_bg_color(ui_ImageWifiSignal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageWifiSignal, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Hilangkan border agar benar-benar bulat
    lv_obj_set_style_border_width(ui_ImageWifiSignal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_remove_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_CLICKABLE);     /// Tidak bisa diklik
    lv_obj_remove_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 170);
    lv_obj_set_height(ui_Button1, 47);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 55);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Button1, button_cb_call_midtrans, LV_EVENT_CLICKED, NULL);

    // =============== START HOTSPOT =========================================
    ui_ButtonHotspot = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonHotspot, 170);
    lv_obj_set_height(ui_ButtonHotspot, 50);
    lv_obj_set_x(ui_ButtonHotspot, -4);
    lv_obj_set_y(ui_ButtonHotspot, -130);
    lv_obj_set_align(ui_ButtonHotspot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonHotspot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonHotspot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Buat button transparan
    lv_obj_set_style_bg_opa(ui_ButtonHotspot, 0, LV_PART_MAIN);     // transparan penuh
    lv_obj_set_style_border_opa(ui_ButtonHotspot, 0, LV_PART_MAIN); // tanpa border
    lv_obj_set_style_shadow_opa(ui_ButtonHotspot, 0, LV_PART_MAIN); // tanpa bayangan

    lv_obj_add_event_cb(ui_ButtonHotspot, hotspot_event_cb, LV_EVENT_ALL, NULL);

    // =============== END HOTSPOT =========================================

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "CLICK HERE");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Screen2);
    // lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 163);
    lv_obj_set_height(ui_Spinner2, 153);
    lv_obj_set_x(ui_Spinner2, 8);
    lv_obj_set_y(ui_Spinner2, -12);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);

    // Warna bagian berputar (indikator) coklat tua
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xFF2600), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Nonaktifkan klik
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);

    // Pindahkan spinner ke layer paling atas agar tidak tertutup button
    lv_obj_move_foreground(ui_Spinner2);

    // Sembunyikan spinner (init tersembunyi)
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
}

// Tambahkan event handler
void hotspot_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_PRESSED) {
        // Catat waktu saat tombol ditekan
        press_start_time = lv_tick_get();
    }

    if (code == LV_EVENT_RELEASED) {
        // Hitung durasi tekan
        uint32_t duration = lv_tick_elaps(press_start_time);

        if (duration >= 1000) {
            DEBUG_PRINTLN("Tombol ditekan dan ditahan 1 detik, buka halaman...");
            lv_async_call(go_page7, NULL);
        } else {
            DEBUG_PRINTLN("Tahan kurang dari 1 detik!");
        }
    }
}

void payment_request_task(void *pvParameters)
{
    char *post_request = (char *)pvParameters;
    
    // Safety check for null parameter
    if (post_request == NULL) {
        DEBUG_PRINTLN("ERROR: payment_request_task received NULL parameter");
        active_payment_tasks--;
        payment_task_running = false;
        lv_async_call(payment_complete_callback, NULL);
        vTaskDelete(NULL);
        return;
    }
    
    DEBUG_PRINTLN("Payment task started with request: %s", post_request);
    
    // Increment active task counter
    active_payment_tasks++;
    
    // Add delay at start to ensure UI is updated and UART is ready
    vTaskDelay(pdMS_TO_TICKS(200));
    
    int32_t is_wifiorlan = 0;
    const char *nvs_namespace = "storage";
    load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
    
    if (is_wifiorlan == NETWORK_LAN) // using LAN
    {
        DEBUG_PRINTLN("Request Using LAN");
        /*bool lan_result = */send_at_command(post_request);
        //DEBUG_PRINTLN("LAN request completed with result: %s", lan_result ? "success" : "failed");
        
        // For LAN, shorter delay since UART response is faster
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
    else if (is_wifiorlan == NETWORK_WIFI) // using WiFi
    { 
        DEBUG_PRINTLN("Request Using Wi-Fi");
        make_http_request(post_request);
        
        // For WiFi, moderate delay since HTTP processing can take time
        // But if successful, execute_payment will redirect to page 8 automatically
        DEBUG_PRINTLN("Waiting for HTTP response processing...");
        vTaskDelay(pdMS_TO_TICKS(5000)); // 5 second delay - reasonable for HTTP processing
    }
    else
    {
        DEBUG_PRINTLN("Network connection not configured (is_wifiorlan = %d)", (int)is_wifiorlan);
        // Add small delay even for error case
        vTaskDelay(pdMS_TO_TICKS(500));
    }
    
    // Clean up allocated memory and decrement counter
    DEBUG_PRINTLN("Freeing allocated post_request memory at: %p", post_request);
    free(post_request);
    post_request = NULL; // Set to NULL after free for safety
    
    active_payment_tasks--;
    payment_task_running = false;
    
    DEBUG_PRINTLN("Payment task cleanup completed, re-enabling UI...");
    
    // Re-enable UI elements after request completion using async call
    // Note: If payment was successful, user will be redirected to page 8 by execute_payment
    // This cleanup is mainly for failed requests or to restore UI state
    lv_async_call(payment_complete_callback, NULL);
    
    vTaskDelete(NULL);
}

void button_cb_call_midtrans(lv_event_t *e)
{
    DEBUG_PRINTLN("=== PAYMENT BUTTON CLICKED ===");
    DEBUG_PRINTLN("payment_task_running: %s", payment_task_running ? "true" : "false");
    DEBUG_PRINTLN("active_payment_tasks: %d", active_payment_tasks);
    
    // CRITICAL: Prevent any clicks if task is already running or button is disabled
    if (payment_task_running || active_payment_tasks > 0) {
        DEBUG_PRINTLN("Payment task already running, ignoring click");
        return;
    }
    
    // Additional check: ensure button is actually clickable
    if (!lv_obj_has_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE)) {
        DEBUG_PRINTLN("Button not clickable, ignoring click");
        return;
    }
    
    // IMMEDIATELY disable button to prevent any further clicks
    DEBUG_PRINTLN("Disabling button immediately to prevent double-clicks");
    lv_obj_add_state(ui_Button1, LV_STATE_DISABLED);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT); // Gray color
    
    // Show spinner immediately
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_move_foreground(ui_Spinner2);
    
    // Set task running flag immediately
    payment_task_running = true;

    DEBUG_PRINTLN("=== DEVICE INFO DEBUG ===");
    DEBUG_PRINTLN("GrossAmountTc: %s (len=%d)", DEVICE_INFO.GrossAmountTc, strlen(DEVICE_INFO.GrossAmountTc));
    DEBUG_PRINTLN("UnitSn: %s (len=%d)", DEVICE_INFO.UnitSn, strlen(DEVICE_INFO.UnitSn));
    DEBUG_PRINTLN("Area: %s (len=%d)", DEVICE_INFO.Area, strlen(DEVICE_INFO.Area));
    DEBUG_PRINTLN("Location: %s (len=%d)", DEVICE_INFO.Location, strlen(DEVICE_INFO.Location));

    // CRITICAL: Detect corrupted DEVICE_INFO and reset to safe defaults
    bool device_info_corrupted = false;
    
    if (strlen(DEVICE_INFO.GrossAmountTc) > 20) {
        DEBUG_PRINTLN("ERROR: GrossAmountTc corrupted! Resetting to default.");
        device_info_corrupted = true;
    }
    
    if (strlen(DEVICE_INFO.UnitSn) > 50) {
        DEBUG_PRINTLN("ERROR: UnitSn corrupted! Resetting to default.");
        device_info_corrupted = true;
    }
    
    if (strlen(DEVICE_INFO.Location) > 50) {
        DEBUG_PRINTLN("ERROR: Location corrupted! Resetting to default.");
        device_info_corrupted = true;
    }
    
    if (strlen(DEVICE_INFO.Area) > 50) {
        DEBUG_PRINTLN("ERROR: Area corrupted! Resetting to default.");
        device_info_corrupted = true;
    }
    
    if (device_info_corrupted) {
        DEBUG_PRINTLN("CRITICAL: DEVICE_INFO corrupted, aborting payment to prevent crash!");
        // Reset task flag and re-enable button
        payment_task_running = false;
        lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
        lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Restore red color
        lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
        return;
    }

    // Safety check for DEVICE_INFO fields - ensure they are valid and reasonable length
    const char *safe_amount = "0";
    const char *safe_unit = "UNKNOWN";
    const char *safe_location = "UNKNOWN";
    const char *safe_area = "UNKNOWN";
    
    if (strlen(DEVICE_INFO.GrossAmountTc) > 0 && strlen(DEVICE_INFO.GrossAmountTc) < 20) {
        // Additional check: ensure string contains only valid characters
        bool valid = true;
        for (int i = 0; i < strlen(DEVICE_INFO.GrossAmountTc); i++) {
            char c = DEVICE_INFO.GrossAmountTc[i];
            if (!(c >= '0' && c <= '9') && c != '.' && c != ',') {
                valid = false;
                break;
            }
        }
        if (valid) safe_amount = DEVICE_INFO.GrossAmountTc;
    }
    
    if (strlen(DEVICE_INFO.UnitSn) > 0 && strlen(DEVICE_INFO.UnitSn) < 30) {
        safe_unit = DEVICE_INFO.UnitSn;
    }
    
    if (strlen(DEVICE_INFO.Location) > 0 && strlen(DEVICE_INFO.Location) < 30) {
        safe_location = DEVICE_INFO.Location;
    }
    
    if (strlen(DEVICE_INFO.Area) > 0 && strlen(DEVICE_INFO.Area) < 30) {
        safe_area = DEVICE_INFO.Area;
    }

    // Use larger static buffer to prevent overflow
    static char post_request[512]; // Increased from 200 to 512
    memset(post_request, 0, sizeof(post_request)); // Clear buffer
    
    int written = snprintf(post_request, sizeof(post_request),
             "<PAYMENT,%s,%s,%s,%s>", // <PAYMENT,AMOUNT,UNIT_SN,LOCATION,AREA>
             safe_amount, safe_unit, safe_location, safe_area);
             
    // Check if snprintf was successful and didn't truncate
    if (written >= sizeof(post_request)) {
        DEBUG_PRINTLN("ERROR: post_request buffer too small, truncated! written=%d, buffer_size=%d", written, sizeof(post_request));
        // Reset task flag and re-enable button on error
        payment_task_running = false;
        lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
        lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Restore red color
        lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
        return;
    }
    
    DEBUG_PRINTLN("Generated payment request: %s (len=%d)", post_request, strlen(post_request));

    // Create a copy of post_request for the task (will be freed in task)
    char *post_request_copy = malloc(strlen(post_request) + 1);
    if (post_request_copy != NULL && active_payment_tasks < MAX_CONCURRENT_PAYMENT_TASKS)
    {
        strcpy(post_request_copy, post_request);
        // payment_task_running is already set to true earlier in the function
        
        // Add longer delay to ensure previous HTTP connections are closed properly
        // This helps prevent "Failed to decode multiple lines" error on consecutive requests
        vTaskDelay(pdMS_TO_TICKS(200));
        
        // Create task to handle network request without blocking UI
        BaseType_t result = xTaskCreate(payment_request_task, "payment_request_task", 8192, post_request_copy, 5, NULL);
        if (result != pdPASS)
        {
            DEBUG_PRINTLN("Failed to create payment request task");
            free(post_request_copy);
            payment_task_running = false;
            // Re-enable button on error
            lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
            lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
            lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Restore red color
            lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
        }
    }
    else
    {
        if (post_request_copy != NULL) free(post_request_copy);
        DEBUG_PRINTLN("Payment task limit reached or memory allocation failed");
        // Reset task flag and re-enable button on error
        payment_task_running = false;
        lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
        lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Restore red color
        lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
    }

    DEBUG_PRINTLN("Payment Click");
}

// Callback untuk mengembalikan UI ke kondisi normal setelah payment selesai
void payment_complete_callback(void *param)
{
    DEBUG_PRINTLN("=== PAYMENT COMPLETE CALLBACK ===");
    
    // Hide spinner
    if (ui_Spinner2 != NULL) {
        lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);
        DEBUG_PRINTLN("Spinner hidden");
    }
    
    // Re-enable button dengan debugging
    if (ui_Button1 != NULL) {
        lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
        lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
        
        // Pastikan button ada di layer yang tepat dan terlihat
        lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_to_index(ui_Button1, 1); // Pastikan index konsisten
        
        // Restore original button color
        lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        
        DEBUG_PRINTLN("Button re-enabled: clickable=%s, hidden=%s", 
               lv_obj_has_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE) ? "true" : "false",
               lv_obj_has_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN) ? "true" : "false");
    }
    
    // Reset task variables dengan debugging
    payment_task_running = false;
    active_payment_tasks = 0;
    DEBUG_PRINTLN("Task variables reset: payment_task_running=%s, active_payment_tasks=%d", 
           payment_task_running ? "true" : "false", active_payment_tasks);
    
    DEBUG_PRINTLN("Payment request completed - UI restored");
}

// WiFi signal blinking timer callback
void wifi_blink_timer_cb(lv_timer_t *timer)
{
    if (ui_ImageWifiSignal == NULL) {
        DEBUG_PRINTLN("WiFi blink timer: ui_ImageWifiSignal is NULL");
        return;
    }
    
    if (timer == NULL) {
        DEBUG_PRINTLN("WiFi blink timer: timer is NULL");
        return;
    }
    
    wifi_blink_state = !wifi_blink_state;
    DEBUG_PRINTLN("WiFi blink timer: state = %s", wifi_blink_state ? "visible" : "hidden");
    
    if (wifi_blink_state) {
        lv_obj_clear_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_HIDDEN);
        // Pastikan selalu di layer paling atas saat muncul
        lv_obj_move_foreground(ui_ImageWifiSignal);
    } else {
        lv_obj_add_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_HIDDEN);
    }
}

// Periodic WiFi status check timer callback
void wifi_status_check_timer_cb(lv_timer_t *timer)
{
    // Add safety check
    if (timer == NULL || ui_ImageWifiSignal == NULL) {
        DEBUG_PRINTLN("WiFi status check timer callback: Invalid timer or UI object");
        return;
    }
    
    // Check network type first - don't run WiFi checks if LAN mode is active
    int32_t is_wifiorlan = 0;
    const char *nvs_namespace = "storage";
    esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
    
    if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
        // Use static counter to reduce log frequency for timer callbacks
        static int lan_log_counter = 0;
        if (++lan_log_counter % 12 == 0) {  // Log every 12 times (60 seconds)
            DEBUG_PRINTLN("LAN mode active - skipping WiFi status check");
        }
        return;
    }
    
    // Reduce logging frequency for timer callbacks
    static int timer_log_counter = 0;
    if (++timer_log_counter % 6 == 0) {  // Log every 6 times (30 seconds)
        DEBUG_PRINTLN("WiFi status check timer running...");
    }
    
    // Update WiFi signal indicator based on current status
    update_wifi_signal_indicator();
}

// Simple function to check internet connectivity
bool check_internet_connectivity(void)
{
    DEBUG_PRINTLN("Checking internet connectivity...");
    
    // Check network type first
    int32_t is_wifiorlan = 0;
    const char *nvs_namespace = "storage";
    esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
    
    if (err != ESP_OK) {
        DEBUG_PRINTLN("Failed to load is_wifiorlan from NVS, assuming no network");
        return false;
    }
    
    DEBUG_PRINTLN("Network type: %d (0=not configured, 1=WiFi, 2=LAN)", (int)is_wifiorlan);
    
    if (is_wifiorlan == NETWORK_WIFI) {
        // For WiFi, check if connected first
        bool wifi_connected = (my_wifi_is_connected() == 1);
        DEBUG_PRINTLN("WiFi connection status: %s", wifi_connected ? "connected" : "not connected");
        
        if (!wifi_connected) {
            return false; // No WiFi connection
        }
        
        // WiFi connected, now test actual internet connectivity
        DEBUG_PRINTLN("WiFi connected, testing internet connectivity...");
        
        // Try to send a simple ping/test request to check internet
        char server_host[64] = {0};
        load_nvs_str(nvs_namespace, "server_host", server_host, sizeof(server_host));
        
        if (strlen(server_host) > 0) {
            // Test with configured server
            DEBUG_PRINTLN("Testing internet with configured server: %s", server_host);
            char *response = my_wifi_send_getinfo_request(server_host, "<PING>");
            
            if (response != NULL) {
                DEBUG_PRINTLN("Internet connectivity test successful");
                // Don't need to free response as my_wifi_send_getinfo_request manages memory
                return true;
            } else {
                DEBUG_PRINTLN("Internet connectivity test failed - no response from server");
                return false;
            }
        } else {
            DEBUG_PRINTLN("No server configured for internet test, assuming connected");
            return wifi_connected;
        }
    } else if (is_wifiorlan == NETWORK_LAN) {
        // For LAN, assume connected (no easy way to check)
        DEBUG_PRINTLN("LAN mode - assuming connected");
        return true;
    }
    
    // Network not configured
    DEBUG_PRINTLN("Network not configured");
    return false;
}

void update_wifi_signal_indicator(void)
{
    DEBUG_PRINTLN("update_wifi_signal_indicator called");
    
    // Check network type first - disable WiFi signal indicator if LAN mode is active
    int32_t is_wifiorlan = 0;
    const char *nvs_namespace = "storage";
    esp_err_t err = load_nvs_i32(nvs_namespace, "is_wifiorlan", &is_wifiorlan);
    
    if (err == ESP_OK && is_wifiorlan == NETWORK_LAN) {
        DEBUG_PRINTLN("LAN mode active - disabling WiFi signal indicator");
        
        // Hide WiFi signal indicator for LAN mode
        if (ui_ImageWifiSignal != NULL) {
            lv_obj_add_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_HIDDEN);
        }
        
        // Stop any existing blinking timer
        if (wifi_blink_timer != NULL) {
            lv_timer_delete(wifi_blink_timer);
            wifi_blink_timer = NULL;
        }
        
        // Show button for payment (always available in LAN mode)
        if (ui_Button1 != NULL) {
            lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN);
            
            // Enable button if no payment task is running
            if (!payment_task_running && active_payment_tasks == 0) {
                lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
                lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
            }
            
            // Restore original red color for LAN mode
            lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        if (ui_Label2 != NULL) {
            lv_label_set_text(ui_Label2, "CLICK HERE");
            lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        
        DEBUG_PRINTLN("LAN mode setup completed - WiFi indicator disabled");
        return;
    }
    
    // Safety check
    if (ui_ImageWifiSignal == NULL) {
        DEBUG_PRINTLN("WiFi signal indicator object is NULL");
        return;
    }
    
    // Stop any existing blinking timer
    if (wifi_blink_timer != NULL) {
        lv_timer_delete(wifi_blink_timer);
        wifi_blink_timer = NULL;
        DEBUG_PRINTLN("Deleted existing blink timer");
    }
    
    // Check if we have internet connectivity
    bool connected = check_internet_connectivity();
    DEBUG_PRINTLN("Internet connectivity check result: %s", connected ? "true" : "false");
    
    if (connected) 
    {
        // Connected to network with internet - hide indicator
        lv_obj_add_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_HIDDEN);
        DEBUG_PRINTLN("Network connected with internet - hiding signal indicator");
        
        // Show button and restore original text
        if (ui_Button1 != NULL) {
            lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN);
            
            // Hanya enable button jika tidak sedang ada payment task yang berjalan
            if (!payment_task_running && active_payment_tasks == 0) {
                lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
                lv_obj_clear_state(ui_Button1, LV_STATE_DISABLED);
                DEBUG_PRINTLN("Button enabled for payment");
            } else {
                DEBUG_PRINTLN("Payment task running, keeping button disabled");
            }
            
            // Move button behind spinner but in front of background image (index 1)
            lv_obj_move_to_index(ui_Button1, 1);
            // Restore original red color when network is available
            lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
            DEBUG_PRINTLN("Showing payment button behind spinner");
        }
        if (ui_Label2 != NULL) {
            lv_label_set_text(ui_Label2, "CLICK HERE");
            // Move label behind spinner but in front of button (index 2)
            lv_obj_move_to_index(ui_Label2, 2);
            // Set text color to white when showing "CLICK HERE"
            lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
            DEBUG_PRINTLN("Button text changed to: CLICK HERE (task_running=%s)", payment_task_running ? "true" : "false");
        }
    } 
    else 
    {
        // No internet connectivity - show blinking red circle
        lv_obj_clear_flag(ui_ImageWifiSignal, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_ImageWifiSignal); // Pastikan di layer paling atas
        wifi_blink_state = true;
        
        // Create blink timer with safety check
        wifi_blink_timer = lv_timer_create(wifi_blink_timer_cb, 500, NULL);
        if (wifi_blink_timer != NULL) {
            DEBUG_PRINTLN("Created WiFi blink timer successfully");
        } else {
            DEBUG_PRINTLN("Failed to create WiFi blink timer");
        }
        DEBUG_PRINTLN("No internet connectivity - showing blinking signal indicator");
        
        // Show button but make it non-clickable and change text to CASH ONLY
        if (ui_Button1 != NULL) {
            lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_HIDDEN);
            lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE);
            lv_obj_move_foreground(ui_Button1); // Pastikan di layer paling atas
            // Change button color to gray to indicate it's disabled
            lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
            DEBUG_PRINTLN("Showing non-clickable button for cash payment");
        }
        if (ui_Label2 != NULL) {
            lv_label_set_text(ui_Label2, "CASH ONLY");
            lv_obj_move_foreground(ui_Label2); // Pastikan label di atas
            // Set text color to black when showing "CASH ONLY"
            lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            DEBUG_PRINTLN("Button text changed to: CASH ONLY");
        }
    }
}